[project]
name = "fastapi-webchat"
version = "0.1.0"
description = "FastAPI backend chat application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "jinja2",
    "pwdlib[bcrypt]",
    "bcrypt",
    "pydantic[email]",
    "aiosqlite",
    "PyJWT",
    "websockets",
    "python-multipart",
    "python-dotenv"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]
